STDOUT:


STDERR:
Traceback (most recent call last):
  File "C:\Users\Usuario\Documents\Practica-3-IA\2-Models-Predictius\Absencies\model_absencies.py", line 113, in <module>
    main()
    ~~~~^^
  File "C:\Users\Usuario\Documents\Practica-3-IA\2-Models-Predictius\Absencies\model_absencies.py", line 79, in main
    data = load_data()
  File "C:\Users\Usuario\Documents\Practica-3-IA\2-Models-Predictius\Absencies\model_absencies.py", line 31, in load_data
    return pd.read_csv(DATA_PATH)
           ~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\Usuario\Documents\Practica-3-IA\.venv\Lib\site-packages\pandas\io\parsers\readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\Usuario\Documents\Practica-3-IA\.venv\Lib\site-packages\pandas\io\parsers\readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\Usuario\Documents\Practica-3-IA\.venv\Lib\site-packages\pandas\io\parsers\readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Documents\Practica-3-IA\.venv\Lib\site-packages\pandas\io\parsers\readers.py", line 1880, in _make_engine
    self.handles = get_handle(
                   ~~~~~~~~~~^
        f,
        ^^
    ...<6 lines>...
        storage_options=self.options.get("storage_options", None),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Usuario\Documents\Practica-3-IA\.venv\Lib\site-packages\pandas\io\common.py", line 873, in get_handle
    handle = open(
        handle,
    ...<3 lines>...
        newline="",
    )
FileNotFoundError: [Errno 2] No such file or directory: '../../portuguese_hs_students.csv'
